### ISSUE TITLE
No database directory

### ISSUE THREAD

**Issue by bradbell** [zhengp0/discover_dismod_at#1]
I cloned the repository and tried to run check_all.py and got the error below.
I had to create the 'database' directory in order to get check_all.py to work.

dismod_at_test.git>python3 check_all.py
Traceback (most recent call last):
  File "check_all.py", line 30, in <module>
  ok = run_test(name, program)
  File "check_all.py", line 13, in run_test
    exec('ok = '   + name + '.' + name + '(program)', namespace)
  File "<string>", line 1, in <module>
  File "./tests/mulcov/gamma_add_std_scale_all.py", line 156, in gamma_add_std_scale_all
    option_table
  File "/home/bradbell/prefix/dismod_at/lib/python3.6/site-packages/dismod_at/create_database.py", line 377, in create_database
    connection     = dismod_at.create_connection(file_name, new)
  File "/home/bradbell/prefix/dismod_at/lib/python3.6/site-packages/dismod_at/create_connection.py", line 57, in create_connection
    connection = sqlite3.connect(file_name)
sqlite3.OperationalError: unable to open database file

**Comment by zhengp0** [comment]
Thanks very much Brad!
I add the safe guard for the existence of database dir.
Please check commit
0ffca69f78de0d225c596760bb905db5b9a1aa80

**Comment by bradbell** [comment]
Works for me.
